export const industryTypes = [
    "Advertising",
    "AgTech",
    "AI",
    "Analytics",
    "AR/VR",
    "AudioTec",
    "AutoTech",
    "BioTech",
    "Chemical",
    "ClimateTech/CleanTech",
    "Cloud Infrastructure",
    "ConstructionTech",
    "Consumer Internet",
    "Cosmetic",
    "Creator/Passion Economy",
    "Data Services",
    "DeepTech",
    "Developer Tools",
    "Diagnostics",
    "Digital Health",
    "Direct-to-Consume",
    "Drug Deliver",
    "E-commerce",
    "Education",
    "EnergyTech",
    "Enterprise Applications",
    "Enterprise Infrastructure",
    "Enterprise",
    "Entertainment & Sports",
    "Fashion",
    "FinTech",
    "Food and Beverage",
    "Future of Work",
    "Games",
    "Gaming/eSports",
    "Generative Tech/AI",
    "Gig Econom",
    "GovTech",
    "Hardware",
    "Health & Hospital Servic",
    "Health IT",
    "Human Capital/HRTech",
    "Impact",
    "Insurance",
    "IoT",
    "LegalTec",
    "Local Service",
    "Lodging/Hospitality",
    "Logistics",
    "Manufacturing",
    "MarketingTech",
    "Marketplaces",
    "Material Science",
    "Media/Content",
    "Medical Devices",
    "Messaging",
    "Parenting/Familie",
    "Payments",
    "Pharmaceuticals",
    "Real Estate/PropTech",
    "Retail",
    "Robotics",
    "SaaS",
    "Sales & CRM",
    "Security",
    "Semiconductor",
    "Smart Cities/UrbanTech",
    "SMB Software",
    "Social Commerce",
    "Social Networks",
    "Space",
    "Supply Chain Tech",
    "Therapeutic",
    "TransportationTech",
    "Travel",
    "Web3/Blockchain ",
    "Web3/Crypto",
    "Wellness & Fitness",
  ];
  
  export const roundTypes = [
    "Pre-seed",
    "Seed",
    "Post-seed",
    "Series A",
    "Series B",
  ];
  
  export const organizationSize = [
    "0-10",
    "10-50",
    "50-100",
    "100-500",
    "500-1000",
    "1000-5000",
    "5000-10000",
    "10000+",
  ];

  
  export const investmenRange = [
    ''
  ]